--- 
- hosts: demo
  tasks:
        - replace:
                path: /etc/httpd/conf/httpd.conf
                regexp: 'Listen 80'
                replace: 'Listen 8080'
        - service: name=httpd state=restarted
